spring.output.ansi.enabled: ALWAYS

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: true
    generate-ddl: true
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

---
spring.output.ansi.enabled: ALWAYS

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true
    generate-ddl: true
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:mysql://localhost:3306/mayoauction?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver